services:
  postgres:
    image: postgres:16-alpine
    container_name: task-workflow-pg
    environment:
      POSTGRES_DB: task-workflow
      POSTGRES_USER: task_user
      POSTGRES_PASSWORD: task_pass
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U task_user -d task-workflow" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
